Controllers/AccountData/DataGet/GetAccountDataController.cs
using ComputerStore.Services.Cache.User;
using ComputerStore_MSSQL.Data.Entities;
using ComputerStore_MSSQL.Data.Repositories.Review;
using ComputerStore_MSSQL.Data.Repositories.Transaction;
using ComputerStore_MSSQL.Data.UnitOfWork;
using Microsoft.AspNetCore.Mvc;

namespace ComputerStore.Controllers.AccountData.DataGet
{
    public class GetAccountDataController : Controller
    {
        private readonly UserCacheService _userCacheService;
        private readonly IUnitOfWork _unitOfWork;
        public GetAccountDataController(UserCacheService userCacheService, IUnitOfWork unitOfWork)
        {
            _userCacheService = userCacheService;
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public async Task<IActionResult> OrdersData()
        {
            string userId = _userCacheService.GetUserId(User.Identity!.Name!);
            var userTransactions = await ((ITransactionRepository)_unitOfWork.Repository<TransactionEntity>()).GetAllTransactionsForUserAsync(userId);
            return View(userTransactions);
        }
        [HttpGet]
        public async Task<IActionResult> ReviewsData()
        {
            string userId = _userCacheService.GetUserId(User.Identity!.Name!);
            var userReviews = await ((IReviewRepository)_unitOfWork.Repository<ReviewEntity>()).GetAllReviewsForUserAsync(userId);
            return View(userReviews);
        }
    }
}

Controllers/Authorization/SignUpController.cs
using ComputerStore.Models.DTO;
using ComputerStore.Services.Register;
using ComputerStore.ViewModels;
using ComputerStore_MSSQL.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ComputerStore.Controllers.Authorization
{
    public class SignUpController : Controller
    {
        private readonly SignInManager<UserEntity> _signInManager;
        private readonly UserManager<UserEntity> _userManager;
        private readonly IRegisterService<RegisterViewModel, RegisterResultDto> _registerService;
        public SignUpController(SignInManager<UserEntity> signInManager, UserManager<UserEntity> userManager, IRegisterService<RegisterViewModel, RegisterResultDto> registerService)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _registerService = registerService;
        }
        [HttpGet]
        public IActionResult Register() => View();
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                RegisterResultDto result = await _registerService.Register(model);
                if (result.Succeeded)
                {
                    Response.Cookies.Append("SuccessMessage", result.Message);
                    return Redirect("~/Home/Index");
                }
                else
                    TempData["ErrorRegisterMessage"] = result.Message;
            }
            else
                TempData["ErrorRegisterMessage"] = ModelState.Values.SelectMany(v => v.Errors).FirstOrDefault()?.ErrorMessage;
            return View(model);
        }
        [HttpGet]
        public IActionResult Login() => View();
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, lockoutOnFailure: false);
            if (result.Succeeded)
            {
                Response.Cookies.Append("SuccessMessage", $"Вхід в акаунт {model.UserName} успішний.");
                return Redirect("~/Home/Index");
            }
            else
            {
                TempData["ErrorLoginMessage"] = "Не правильний логін або пароль.";
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return Redirect("~/Home/Index");
        }
    }
}

Controllers/Support/SupportController.cs
using Microsoft.AspNetCore.Mvc;

namespace ComputerStore.Controllers.Support
{
    public class SupportController : Controller
    {
        [HttpGet]
        public IActionResult Support() => View();
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ComputerStore_MSSQL.Data.Entities;
@inject UserManager<UserEntity> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ComputerStore</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,300;0,400;0,500;1,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ComputerStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-RI/fIep0A9X+dOxaJjK7UKCwNlGx7OZwrAascl1KjOGVT6D+NGbV8F1Wm/Xv5x5p5KtDlj8BGB0Mum3qzJ9XQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/css/stylesLayout.css" />
</head>
<body>
    <header>
        <nav class="main-navigation">
            @if (User.Identity!.IsAuthenticated)
            {
                <nav class="hamburger-menu">
                    <div class="menu-icon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    <ul class="menu-items">
                        <li><a asp-area="" asp-controller="UpdateAccountData" asp-action="ChangePassword">Change Password</a></li>
                        <li><a asp-area="" asp-controller="UpdateAccountData" asp-action="ChangeAccountData">Change Account Data</a></li>
                        <li><a asp-area="" asp-controller="GetAccountData" asp-action="OrdersData">Check My Orders</a></li>
                        <li><a asp-area="" asp-controller="GetAccountData" asp-action="ReviewsData">Check My Reviews</a></li>
                        <li><a asp-area="" asp-controller="Support" asp-action="Support" class="support-link">🛈 Support </a></li>
                    </ul>
                    <div class="overlay"></div>
                </nav>
            }
            <a class="store-brand" asp-area="" asp-controller="Home" asp-action="Index">Computer Store</a>
            <div class="search-container">
                <form asp-action="Index" asp-controller="Home" method="get">
                    <input class="search-input" type="text" name="searchQuery" placeholder="Пошук" value="@ViewBag.SearchQuery">
                    <button type="submit" class="search-icon"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="navigation-controllers">
                <form asp-area="" asp-controller="Cart" asp-action="Cart" method="get">
                    <button class="cart-btn"><i class="fas fa-shopping-cart"></i></button>
                </form>
                @if (User.Identity!.IsAuthenticated)
                {
                    var user = await UserManager.FindByNameAsync(User.Identity!.Name!);
                    var userRoles = UserManager.GetRolesAsync(user!).Result;
                    @if (userRoles.Contains("Admin") || userRoles.Contains("Manager"))
                    {
                        <form asp-controller="Admin" asp-action="AdminIndex" method="get">
                            <button class="btn" style="margin-right: 15px;">Manager Panel</button>
                        </form>
                    }
                }
                <a class="signup-link" asp-area="" asp-controller="SignUp" asp-action="Register">Register</a>
                @if (User.Identity!.IsAuthenticated)
                {
                    <a class="logout-link" asp-area="" asp-controller="SignUp" asp-action="Logout">Log Out</a>
                }
                else
                {
                    <a class="signup-link" asp-area="" asp-controller="SignUp" asp-action="Login">Login</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script>
        const menuIcon = document.querySelector('.menu-icon');
        const menuItems = document.querySelector('.menu-items');
        const overlay = document.querySelector('.overlay');
        menuIcon.addEventListener('click', () => {
            menuItems.style.left = '0';
            overlay.style.opacity = '1';
            overlay.style.pointerEvents = 'auto';
        });

        overlay.addEventListener('click', () => {
            menuItems.style.left = '-300px';
            overlay.style.opacity = '0';
            overlay.style.pointerEvents = 'none';
        });

        menuItems.addEventListener('click', (event) => {
            event.stopPropagation();
        });
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>