Controllers/Cart/CartController.cs
using ComputerStore.Services.Cache.User;
using ComputerStore.Services.Cart;
using ComputerStore.ViewModels;
using ComputerStore_MSSQL.Data.Entities;
using ComputerStore_MSSQL.Data.Repositories.Cart;
using ComputerStore_MSSQL.Data.Repositories.Product;
using ComputerStore_MSSQL.Data.Repositories.Transaction;
using ComputerStore_MSSQL.Data.UnitOfWork;
using Microsoft.AspNetCore.Mvc;

namespace ComputerStore.Controllers.Cart
{
    public class CartController : Controller
    {
        private readonly UserCacheService _userCacheService;
        private readonly IUnitOfWork _unitOfWork;
        private IEnumerable<ProductEntity> _orderProducts;
        private readonly ICartService _cartService;
        public CartController(UserCacheService userCacheService, IUnitOfWork unitOfWork, ICartService cartService)
        {
            _userCacheService = userCacheService;
            _unitOfWork = unitOfWork;
            _cartService = cartService;
            _orderProducts = new List<ProductEntity>();
        }
        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            if (!User.Identity!.IsAuthenticated)
            {
                Response.Cookies.Append("ErrorIndexMessage", "Щоб відкрити кошик, потрібно увійти в свій акаунт.");
                return Redirect("~/Home/Index");
            }
            string userId = _userCacheService.GetUserId(User.Identity!.Name!);
            _orderProducts = (await ((ICartRepository)_unitOfWork.Repository<CartEntity>()).GetCartForUserAsync(userId))!;
            return View(_orderProducts);
        }
        [HttpPost]
        public async Task<IActionResult> AddToCart(Guid productId, bool inStock)
        {
            if (!User.Identity!.IsAuthenticated)
            {
                Response.Cookies.Append("ErrorIndexMessage", "Щоб додати товар до кошику, потрібно увійти в свій акаунт.");
                return Redirect("~/Home/Index");
            }
            string userId = _userCacheService.GetUserId(User.Identity!.Name!);
            if (inStock)
            {
                if (await ((ICartRepository)_unitOfWork.Repository<CartEntity>()).AddProductToCartAsync(userId, productId))
                    Response.Cookies.Append("SuccessMessage", "Товар успішно додано до вашого кошику.");
                else
                    Response.Cookies.Append("ErrorIndexMessage", "Товар вже наявний у вашому кошику.");
            }
            else
                Response.Cookies.Append("ErrorIndexMessage", "Товару нажаль зараз не має у наявності.");
            return Redirect("~/Home/Index");
        }
        [HttpDelete]
        public async Task<IActionResult> RemoveFromCart(Guid productId)
        {
            string userId = _userCacheService.GetUserId(User.Identity!.Name!);
            await ((ICartRepository)_unitOfWork.Repository<CartEntity>()).RemoveProductFromCartAsync(userId, productId);
            return RedirectToAction("Cart");
        }
        [HttpGet]
        public async Task<IActionResult> BuyProducts()
        {
            string userId = _userCacheService.GetUserId(User.Identity!.Name!);
            _orderProducts = (await ((ICartRepository)_unitOfWork.Repository<CartEntity>()).GetCartForUserAsync(userId))!;
            if (!_orderProducts.All(p => p.InStock))
            {
                Response.Cookies.Append("ErrorIndexMessage", "Одного або декількох товарів з вашого кошику немає в наявності, будь ласка видаліть їх з кошику.");
                return Redirect("~/Home/Index");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BuyProducts(OrderViewModel model)
        {
            string userId = _userCacheService.GetUserId(User.Identity!.Name!);
            await _cartService.CreateOrder(userId, model);
            Response.Cookies.Append("SuccessMessage", "Замовлення успішно відправлене, очікуйте дзвінка менеджера.");
            return Redirect("~/Home/Index");
        }
    }
}

Controllers/Product/ProductClientController.cs
using ComputerStore.ViewModels;
using ComputerStore_MSSQL.Data.Entities;
using ComputerStore_MSSQL.Data.Repositories.Product;
using ComputerStore_MSSQL.Data.UnitOfWork;
using Microsoft.AspNetCore.Mvc;

namespace ComputerStore.Controllers.Product
{
    public class ProductClientController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProductClientController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public async Task<IActionResult> ShowProduct(ProductViewModel productViewModel)
        {
            var product = await ((IProductRepository)_unitOfWork.Repository<ProductEntity>()).GetProductAsync(productViewModel.ProductId);
            return View(product);
        }
    }
}

Views/Cart/BuyProducts.cshtml
@using ComputerStore.ViewModels;
@model OrderViewModel
<form asp-action="BuyProducts" method="post">
    <html>
    <head>
        <link rel="stylesheet" href="~/css/stylesInputForm.css">
    </head>
    <body>
        <div class="box">
            <h1>Order</h1>
            <label>Введіть місто доставки: </label>
            <input asp-for="ShippingCity" type="text" required>
            <label>Введіть адресу доставки: </label>
            <input asp-for="ShippingAddress" type="text" required>
            <label>Введіть поштовий індекс: </label>
            <input asp-for="ShippingPostalCode" type="number" required>
            <button type="submit">Order</button>
        </div>
    </body>
</html>
</form>

Views/Cart/Cart.cshtml
@using ComputerStore_MSSQL.Data.Entities;
@using ComputerStore.ViewModels;
@model IEnumerable<ProductEntity>
<head>
    <link rel="stylesheet" href="~/css/stylesCart.css">
</head>
<body>
    <div class="main-container">
        @if (Model.Count() < 1)
        {
            <h6>Кошик пустий.</h6>
        }
        else
        {
            @foreach (var product in Model)
            {
                <div class="product-container">
                    <a class="product-link" href="@Url.Action("ShowProduct", "ProductClient", new ProductViewModel{ProductId = product.ProductId})">
                        <div class="image-container">
                            <img src="@product.Image" alt="Product Image" />
                        </div>
                        <div class="details-container">
                            <div class="info-container">
                                <h6>@product.Name</h6>
                                @if (product.InStock)
                                {
                                    <p class="inStockTrue">В наявності</p>
                                }
                                else
                                {
                                    <p class="inStockFalse">Немає в наявності</p>
                                }
                                <h5>@product.Price.ToString("N2").TrimEnd('0').TrimEnd(',') грн</h5>
                            </div>
                        </div>
                    </a>
                    <div class="remove-icon-container">
                        <form asp-controller="Cart" asp-action="RemoveFromCart" method="post">
                            <input type="hidden" name="productId" value="@product.ProductId" />
                            <button class="remove-icon" type="submit">&#10006;</button>
                        </form>
                    </div>
                </div>
            }
            <div class="buy-container">
                <h7>Загальна сума товарів: @Model.Sum(p => p.Price)</h7>
                <form asp-controller="Cart" asp-action="BuyProducts" method="get">
                    <button class="buy-btn">Buy</button>
                </form>
            </div>
        }
    </div>
</body>